// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuyuokbpfpsahoilowvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1eXVva2JwZnBzYWhvaWxvd3ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxODEzODAsImV4cCI6MjA2MDc1NzM4MH0.Ac3GVT1e_jfV68V6hj4UX1OLUuSw4JnXkbo8CGsPPE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);